name: 生成 README
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: mcseekeri
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_octicon: yes
          config_timezone: Asia/Shanghai
          config_twemoji: yes
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_followup_indepth: yes
          plugin_followup_archived: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_licenses: yes
          plugin_licenses_legal: yes
          plugin_licenses_ratio: yes
          plugin_lines_sections: base
          plugin_music: yes
          plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
          plugin_music_provider: lastfm
          plugin_music_user: MCSeekeri
          plugin_music_limit: 8
          plugin_music_mode: recent
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_achievements_limit: 4
          plugin_steam_games_limit: 4
          plugin_steam_recent_games_limit: 4
          plugin_steam_sections: player, most-played, recently-played
          plugin_steam_user: "76561198356149041"
          plugin_traffic: yes
          repositories_forks: yes
          repositories_affiliations: owner, collaborator